name: flutter_application_home
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: Discord
      fonts:
        - asset: assets/fonts/ABCGintoDiscord-Regular.ttf
          weight: 400
        - asset: assets/fonts/ABCGintoDiscord-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/ABCGintoDiscord-Medium.ttf
          weight: 500
        - asset: assets/fonts/ABCGintoDiscord-MediumItalic.ttf
          weight: 500
          style: italic

    - family: Handjet
      fonts:
        - asset: assets/fonts/Handjet-Thin.ttf
          weight: 100
        - asset: assets/fonts/Handjet-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Handjet-Light.ttf
          weight: 300
        - asset: assets/fonts/Handjet-Regular.ttf
          weight: 400
        - asset: assets/fonts/Handjet-Medium.ttf
          weight: 500
        - asset: assets/fonts/Handjet-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Handjet-Bold.ttf
          weight: 700
        - asset: assets/fonts/Handjet-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Handjet-Black.ttf
          weight: 900

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/Discord.png"
  image_pathadaptive_icon_foreground: "assets/icon/Discord.png"
  adaptive_icon_background: "#4B0061"
  adaptive_icon_foreground: "assets/icon/Discord.png"